# Generated by Django 3.1.1 on 2020-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('EN', 'Enviado'), ('RV', 'Revisado'), ('RE', 'Reprovado'), ('AP', 'Aprovado')], default='EN', max_length=2),
        ),
    ]
